on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 21.x
      uses: actions/setup-node@v2
      with:
        node-version: 21.x
    - run: npm install
    - run: cp -r /home/c81967/memessenger.na4u.ru/actions-runner/cicd/server/server/dist /home/c81967/memessenger.na4u.ru/app/dist
